/**
 * llm.h - Local generative inference library.
 * Summary: Public API for loading GGUF models and generating text.
 *
 * Author:  KaisarCode
 * Website: https://kaisarcode.com
 * License: https://www.gnu.org/licenses/gpl-3.0.html
 */

#ifndef KC_LLM_H
#define KC_LLM_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct kc_llm kc_llm_t;

#define KC_LLM_OK      0
#define KC_LLM_ERROR  -1
#define KC_LLM_ESTOP  -2

/**
 * Callback that receives generated text bytes.
 * @param data Pointer to the generated bytes.
 * @param len Number of bytes.
 * @param user User pointer passed from the caller.
 * @return 0 on success, non-zero to request stopping generation.
 */
typedef int (*kc_llm_write_fn)(const char *data, size_t len, void *user);

/**
 * Public inspection fields for model and runtime queries.
 */
typedef enum {
    KC_LLM_INFO_ARCHITECTURE = 0,
    KC_LLM_INFO_NAME,
    KC_LLM_INFO_PARAMETERS,
    KC_LLM_INFO_SIZE,
    KC_LLM_INFO_VOCABULARY,
    KC_LLM_INFO_CONTEXT_MAX,
    KC_LLM_INFO_EMBEDDING_SIZE,
    KC_LLM_INFO_LAYERS,
    KC_LLM_INFO_HEADS,
    KC_LLM_INFO_KV_HEADS,
    KC_LLM_INFO_INPUT_TOKENS,
    KC_LLM_INFO_CONTEXT_USED,
    KC_LLM_INFO_CONTEXT_SIZE,
    KC_LLM_INFO_CONTEXT_FREE,
    KC_LLM_INFO_CONTEXT_AFTER
} kc_llm_info_field_t;

/**
 * Value types returned by the inspection API.
 */
typedef enum {
    KC_LLM_INFO_VALUE_NONE = 0,
    KC_LLM_INFO_VALUE_STRING,
    KC_LLM_INFO_VALUE_U64,
    KC_LLM_INFO_VALUE_I64
} kc_llm_info_value_type_t;

/**
 * Input request used for input-dependent inspection fields.
 */
typedef struct {
    const char *role;
    const char *content;
} kc_llm_info_request_t;

/**
 * Typed result for one inspection field.
 * String values are owned by kc_llm_t and remain valid until kc_llm_close().
 */
typedef struct {
    kc_llm_info_field_t field;
    kc_llm_info_value_type_t type;
    union {
        const char *string;
        uint64_t u64;
        int64_t i64;
    } value;
} kc_llm_info_t;

/**
 * Options for creating an LLM context.
 * String fields are deep-copied by kc_llm_open().
 */
typedef struct {
    char *model_path;
    int ctx;
    int predict;
    int threads;
    int gpu;
    int gpu_layers;
    int seed;
    float temp;
    int top_k;
    float top_p;
    float min_p;
    float repeat_penalty;
    int repeat_last_n;
    int until;
    char *kv_load_path;
    char *kv_save_path;
    char **lora_paths;
    float *lora_scales;
    int n_loras;
    char *mmproj_path;
    char **images;
    int n_images;
    char *role;
    int think;
    char *mtp_path;
    int mtp_tokens;
    int mtp_min;
    float mtp_p_split;
    float mtp_p_min;
    int mtp_threads;
    int mtp_gpu_layers;
    int fattn;
} kc_llm_options_t;

/**
 * Return default options.
 * @return Default-initialized options struct.
 */
kc_llm_options_t kc_llm_options_default(void);

/**
 * Load configuration overrides from KC_LLM_* environment variables.
 * @param opts Options to update.
 * @return None.
 */
void kc_llm_options_load_env(kc_llm_options_t *opts);

/**
 * Release resources owned by an options struct.
 * @param opts Options to clean up (may be NULL).
 * @return None.
 */
void kc_llm_options_free(kc_llm_options_t *opts);

/**
 * Returns the build version generated at compile time.
 * @return Unix timestamp for the current build.
 */
uint64_t kc_llm_version(void);

/**
 * Return the last error message from a context.
 * @param ctx Context pointer.
 * @return Error string, or "null context" if ctx is NULL.
 */
const char *kc_llm_error(const kc_llm_t *ctx);

/**
 * Initialize a new LLM context.
 * @param out Pointer to receive the context pointer.
 * @param opts Options.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_open(kc_llm_t **out, const kc_llm_options_t *opts);

/**
 * Initialize a model-only context for static inspection.
 * This loads model metadata and vocabulary without creating a
 * generation runtime.
 * @param out Pointer to receive the context pointer.
 * @param opts Options containing at least model_path.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_open_model(kc_llm_t **out, const kc_llm_options_t *opts);

/**
 * Release an LLM context and all associated resources.
 * @param ctx Context pointer.
 * @return None.
 */
void kc_llm_close(kc_llm_t *ctx);

/**
 * Generate text from a prompt.
 * Treats the prompt as user message content, applies a model chat template when
 * available, and falls back to the raw prompt when templating is unavailable.
 * @param ctx Context pointer.
 * @param prompt Null-terminated prompt text.
 * @param write Output callback.
 * @param user User pointer for callback.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_generate(kc_llm_t *ctx, const char *prompt, kc_llm_write_fn write, void *user);

/**
 * Generate text from message content with an explicit role.
 * Applies a model chat template when available and falls back to raw content
 * when templating is unavailable.
 * @param ctx Context pointer.
 * @param role Message role string: system, user, or assistant.
 * @param content Null-terminated message content.
 * @param write Output callback.
 * @param user User pointer for callback.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_generate_role(kc_llm_t *ctx, const char *role, const char *content,
    kc_llm_write_fn write, void *user);

/**
 * Query one or more inspection fields from a loaded model or runtime.
 * Static fields may be queried with request == NULL.
 * Input-dependent fields require request content and use the exact request
 * preparation and tokenization path used by inference.
 * context-used is the current effective context occupancy before the current
 * request. It may include restored KV occupancy and occupancy left by earlier
 * work in the same runtime. context-free is context-size minus context-used.
 * context-after is the projected occupancy after adding the current request and
 * excludes future generated output.
 * @param ctx Context pointer.
 * @param fields Requested field list.
 * @param n_fields Number of requested fields.
 * @param request Optional request for input-dependent fields.
 * @param out Output array with n_fields elements.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_info_query(kc_llm_t *ctx, const kc_llm_info_field_t *fields,
    size_t n_fields, const kc_llm_info_request_t *request, kc_llm_info_t *out);

/**
 * Request stop for a specific context.
 * @param ctx Context pointer.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_stop(kc_llm_t *ctx);

/**
 * Return whether stop was requested for a specific context.
 * @param ctx Context pointer.
 * @return 1 when stop was requested, or 0 otherwise.
 */
int kc_llm_stop_requested(kc_llm_t *ctx);

/**
 * Clear the KV cache and reset generation state.
 * @param ctx Context pointer.
 * @return KC_LLM_OK on success, or KC_LLM_ERROR on failure.
 */
int kc_llm_memory_clear(kc_llm_t *ctx);

#ifdef __cplusplus
}
#endif

#endif
