/**
 * style.h - Markdown ANSI presentation style
 * Summary: Configurable terminal attributes, colors, and block spacing.
 *
 * Author:  KaisarCode
 * Website: https://kaisarcode.com
 * License: https://www.gnu.org/licenses/gpl-3.0.html
 */

#ifndef KC_MDP_STYLE_H
#define KC_MDP_STYLE_H

#ifndef KC_MDP_STYLE_COLOR_HEADING
#define KC_MDP_STYLE_COLOR_HEADING ""
#endif

#ifndef KC_MDP_STYLE_COLOR_TEXT
#define KC_MDP_STYLE_COLOR_TEXT ""
#endif

#ifndef KC_MDP_STYLE_COLOR_LINK
#define KC_MDP_STYLE_COLOR_LINK ""
#endif

#ifndef KC_MDP_STYLE_COLOR_CODE
#define KC_MDP_STYLE_COLOR_CODE ""
#endif

#ifndef KC_MDP_STYLE_COLOR_QUOTE
#define KC_MDP_STYLE_COLOR_QUOTE ""
#endif

#ifndef KC_MDP_STYLE_COLOR_TABLE
#define KC_MDP_STYLE_COLOR_TABLE ""
#endif

#ifndef KC_MDP_STYLE_COLOR_TASK
#define KC_MDP_STYLE_COLOR_TASK ""
#endif

#ifndef KC_MDP_STYLE_COLOR_RESET
#define KC_MDP_STYLE_COLOR_RESET ""
#endif

#ifndef KC_MDP_STYLE_STRONG_OPEN
#define KC_MDP_STYLE_STRONG_OPEN "\x1b[1m"
#endif

#ifndef KC_MDP_STYLE_STRONG_CLOSE
#define KC_MDP_STYLE_STRONG_CLOSE "\x1b[22m"
#endif

#ifndef KC_MDP_STYLE_DIM_OPEN
#define KC_MDP_STYLE_DIM_OPEN "\x1b[2m"
#endif

#ifndef KC_MDP_STYLE_DIM_CLOSE
#define KC_MDP_STYLE_DIM_CLOSE "\x1b[22m"
#endif

#ifndef KC_MDP_STYLE_EM_OPEN
#define KC_MDP_STYLE_EM_OPEN "\x1b[3m"
#endif

#ifndef KC_MDP_STYLE_EM_CLOSE
#define KC_MDP_STYLE_EM_CLOSE "\x1b[23m"
#endif

#ifndef KC_MDP_STYLE_STRIKE_OPEN
#define KC_MDP_STYLE_STRIKE_OPEN "\x1b[9m"
#endif

#ifndef KC_MDP_STYLE_STRIKE_CLOSE
#define KC_MDP_STYLE_STRIKE_CLOSE "\x1b[29m"
#endif

#ifndef KC_MDP_STYLE_CODE_INLINE_OPEN
#define KC_MDP_STYLE_CODE_INLINE_OPEN \
    KC_MDP_STYLE_COLOR_CODE KC_MDP_STYLE_DIM_OPEN
#endif

#ifndef KC_MDP_STYLE_CODE_INLINE_CLOSE
#define KC_MDP_STYLE_CODE_INLINE_CLOSE \
    KC_MDP_STYLE_DIM_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_H1_OPEN
#define KC_MDP_STYLE_H1_OPEN \
    KC_MDP_STYLE_COLOR_HEADING KC_MDP_STYLE_STRONG_OPEN
#endif

#ifndef KC_MDP_STYLE_H1_CLOSE
#define KC_MDP_STYLE_H1_CLOSE \
    KC_MDP_STYLE_STRONG_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_H2_OPEN
#define KC_MDP_STYLE_H2_OPEN \
    KC_MDP_STYLE_COLOR_HEADING KC_MDP_STYLE_STRONG_OPEN
#endif

#ifndef KC_MDP_STYLE_H2_CLOSE
#define KC_MDP_STYLE_H2_CLOSE \
    KC_MDP_STYLE_STRONG_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_H3_OPEN
#define KC_MDP_STYLE_H3_OPEN KC_MDP_STYLE_COLOR_HEADING
#endif

#ifndef KC_MDP_STYLE_H3_CLOSE
#define KC_MDP_STYLE_H3_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_H4_OPEN
#define KC_MDP_STYLE_H4_OPEN \
    KC_MDP_STYLE_COLOR_HEADING KC_MDP_STYLE_DIM_OPEN
#endif

#ifndef KC_MDP_STYLE_H4_CLOSE
#define KC_MDP_STYLE_H4_CLOSE \
    KC_MDP_STYLE_DIM_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_H5_OPEN
#define KC_MDP_STYLE_H5_OPEN KC_MDP_STYLE_H4_OPEN
#endif

#ifndef KC_MDP_STYLE_H5_CLOSE
#define KC_MDP_STYLE_H5_CLOSE KC_MDP_STYLE_H4_CLOSE
#endif

#ifndef KC_MDP_STYLE_H6_OPEN
#define KC_MDP_STYLE_H6_OPEN KC_MDP_STYLE_H4_OPEN
#endif

#ifndef KC_MDP_STYLE_H6_CLOSE
#define KC_MDP_STYLE_H6_CLOSE KC_MDP_STYLE_H4_CLOSE
#endif

#ifndef KC_MDP_STYLE_QUOTE_OPEN
#define KC_MDP_STYLE_QUOTE_OPEN \
    KC_MDP_STYLE_COLOR_QUOTE KC_MDP_STYLE_DIM_OPEN
#endif

#ifndef KC_MDP_STYLE_QUOTE_CLOSE
#define KC_MDP_STYLE_QUOTE_CLOSE \
    KC_MDP_STYLE_DIM_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_CODE_BLOCK_OPEN
#define KC_MDP_STYLE_CODE_BLOCK_OPEN \
    KC_MDP_STYLE_COLOR_CODE KC_MDP_STYLE_DIM_OPEN
#endif

#ifndef KC_MDP_STYLE_CODE_BLOCK_CLOSE
#define KC_MDP_STYLE_CODE_BLOCK_CLOSE \
    KC_MDP_STYLE_DIM_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_TABLE_HEADER_OPEN
#define KC_MDP_STYLE_TABLE_HEADER_OPEN \
    KC_MDP_STYLE_COLOR_TABLE KC_MDP_STYLE_STRONG_OPEN
#endif

#ifndef KC_MDP_STYLE_TABLE_HEADER_CLOSE
#define KC_MDP_STYLE_TABLE_HEADER_CLOSE \
    KC_MDP_STYLE_STRONG_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_LINK_OPEN
#define KC_MDP_STYLE_LINK_OPEN KC_MDP_STYLE_COLOR_LINK
#endif

#ifndef KC_MDP_STYLE_LINK_CLOSE
#define KC_MDP_STYLE_LINK_CLOSE KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_PARAGRAPH_GAP
#define KC_MDP_STYLE_PARAGRAPH_GAP "\n\n"
#endif

#ifndef KC_MDP_STYLE_HEADING_GAP
#define KC_MDP_STYLE_HEADING_GAP "\n\n"
#endif

#ifndef KC_MDP_STYLE_LIST_GAP
#define KC_MDP_STYLE_LIST_GAP "\n"
#endif

#ifndef KC_MDP_STYLE_QUOTE_GAP
#define KC_MDP_STYLE_QUOTE_GAP "\n"
#endif

#ifndef KC_MDP_STYLE_CODE_BLOCK_GAP
#define KC_MDP_STYLE_CODE_BLOCK_GAP "\n\n"
#endif

#ifndef KC_MDP_STYLE_TABLE_GAP
#define KC_MDP_STYLE_TABLE_GAP "\n"
#endif

#ifndef KC_MDP_STYLE_HORIZONTAL_RULE_GAP
#define KC_MDP_STYLE_HORIZONTAL_RULE_GAP "\n"
#endif

#ifndef KC_MDP_STYLE_LIST_BULLET
#define KC_MDP_STYLE_LIST_BULLET "  • "
#endif

#ifndef KC_MDP_STYLE_TASK_OFF
#define KC_MDP_STYLE_TASK_OFF \
    KC_MDP_STYLE_COLOR_TASK "  ☐ " KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_TASK_ON
#define KC_MDP_STYLE_TASK_ON \
    KC_MDP_STYLE_COLOR_TASK "  ☑ " KC_MDP_STYLE_COLOR_RESET
#endif

#ifndef KC_MDP_STYLE_CODE_INDENT
#define KC_MDP_STYLE_CODE_INDENT "  "
#endif

#ifndef KC_MDP_STYLE_TABLE_SEPARATOR
#define KC_MDP_STYLE_TABLE_SEPARATOR " │ "
#endif

#ifndef KC_MDP_STYLE_HORIZONTAL_RULE
#define KC_MDP_STYLE_HORIZONTAL_RULE \
    "────────────────────────────────────────\n"
#endif

#endif
